apiVersion: batch/v1
kind: Job
metadata:
  name: Zusatzaufgabe
spec:
  template:
    spec:
      containers:
      - name: Hello World
        image: 
        command: ["echo", "Hello World"]
      restartPolicy: Never
  backoffLimit: 4